### ISSUE TITLE
JndiLoader Incorrectly reports no JNDI Context

### ISSUE THREAD

**Issue by ee-usgs** [eeverman/andhow#207]
Running Glassfish 4.1 on Java 8.

Glassfish apparently does not create the standard 'java:comp/env' namespace for its jndi resources.  This results in a NamingException being thrown in the JndiLoader from this line:
`Object o = ctx.lookup(JNDI_PROTOCOL_NAME + root + propName);`

It would be expected that there would be some `NameNotFoundException`'s and these are handled separately, so its very possible this is Glassfish specific issue because the `NamingException` that is thrown contains a rootException of `NameNotFoundException`  Its also possible that this is standard behaviour when the root (in this case 'java:comp/' is not found - not clear if that is considered a bigger error than just not finding the complete name.

ref:  https://stackoverflow.com/questions/30849292/how-to-set-a-javacomp-env-foo-jndi-variable-in-glassfish-4-1

**Comment by eeverman** [comment]
Fixed by PR from Issue207.
