### ISSUE TITLE
Validators should clearer policy for null values

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#361]
Currently, validation (eg greaterThanOrEqualTo) will return `false` for a null value.  The null value never happens because AndHowCore only attempts to validate values for which a non-null value was found.

I think this should switch to allowing a null-pointer to be throw for a null.  There is no recovery when a Loader behaves incorrectly and passes a null.  Neither possible return value (true of false) is a correct behavior and it will likely lead to more errors later in the construction cycle.  Better to throw the error where it is first detected.

**Comment by rupeshA** [comment]
@eeverman , see PR https://github.com/eeverman/andhow/pull/394

**Comment by eeverman** [comment]
Note that PR #394 does not address this issue, it addressed #362.  This task is to deal with the logic where Validators are used so that a null response from a validator does not cause an error and is not considered `false`.

**Comment by eeverman** [comment]
fixed by #706
