### ISSUE TITLE
Validator.isValid should return a boxed Boolean

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#362]
**_This issue needs to be handled on the 0.5.0 branch._**

Currently returns a primitive boolean.  This comes up a bit short if we add OR logic in the future because cases of math validation (>4) must return true or false - they cannot abstain with a null if the value is null, leaving the isNullAllowed flag to decide if the value is valid.

**Comment by eeverman** [comment]
See #361

**Comment by rupeshA** [comment]
@eeverman , May I take this one ? https://github.com/eeverman/andhow/pull/394

**Comment by eeverman** [comment]
Fixed by #394
