### ISSUE TITLE
Remove one constructor from org.yarnandtail.andhow.service.PropertyRegistration

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#374]
The constructor `PropertyRegistration(String classCanonName, String propName, List<String> innerPathNesting)` is only used one place.  Remove this constructor and update the single place it is used to use a different constructor:
`org.yarnandtail.andhow.service.PropertyRegistrationList:128` should use the array style constructor instead.  That might look like this:
```
PropertyRegistration reg = new PropertyRegistration(
	rootCanonName, name, innerPath.toArray(new String[innerPath.size()]));
```

**Comment by mattkimmel** [comment]
Done in PR #378!
