### ISSUE TITLE
ReadMe code sample should include main args

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#376]
Don't use a separate method - just put it all in main.

**Comment by RiotPharaoh** [comment]
Hi, could you tell me more information about your issue?

**Comment by eeverman** [comment]
Hi @RiotPharaoh - Thanks for your interest in helping.
This particular task is about better demonstrating a key feature of AndHow on the GitHub home page.  I think I will need to do this task - I have several tasks that are labeled **helpwanted** or **goodfirstissue**.
