### ISSUE TITLE
AndHowLog needs better unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#387]
`org.yarnandtail.andhow.util.AndHowLog` has a unit test already (AndHowLogTest), however, [it does not cover all of the code and methods completely](https://codecov.io/gh/eeverman/andhow/src/master/andhow-core/src/main/java/org/yarnandtail/andhow/util/AndHowLog.java).

Add tests to cover all methods, as well as probe null and empty parameters.  New testing should be added to the existing unit test class.

**Comment by rupeshA** [comment]
@eeverman , have a look at the PR https://github.com/eeverman/andhow/pull/396

**Comment by eeverman** [comment]
Fixed by #396
