### ISSUE TITLE
TextUtil needs better unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#388]
`org.yarnandtail.andhow.util.TextUtil` has a unit test (TextUtilTest), however, [it does not cover all code and methods](https://codecov.io/gh/eeverman/andhow/src/master/andhow-core/src/main/java/org/yarnandtail/andhow/util/TextUtil.java).

Add tests that cover all code and methods to the existing TextUtilTest class.

**Comment by shouxian92** [comment]
I think i'll take up this one too

**Comment by eeverman** [comment]
Fixed by #398
