### ISSUE TITLE
IntValidator needs better unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#390]
`org.yarnandtail.andhow.valid.IntValidator` has a unit test (IntValidatorTest), however [it does not test all code and methods](https://codecov.io/gh/eeverman/andhow/src/master/andhow-core/src/main/java/org/yarnandtail/andhow/valid/IntValidator.java).

Extend the existing unit test class to cover all code and methods.

**Comment by jr7square** [comment]
I can look into this one

**Comment by eeverman** [comment]
Fixed by #399
