### ISSUE TITLE
DblValidator needs better unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#392]
`org.yarnandtail.andhow.valid.DblValidator` has a unit test (DblValidatorTest), however [it does not test all code and methods](https://codecov.io/gh/eeverman/andhow/src/master/andhow-core/src/main/java/org/yarnandtail/andhow/valid/DblValidator.java).

Extend the existing unit test class to cover all code and methods.

**Comment by shouxian92** [comment]
I'd like to take this up 😊

**Comment by eeverman** [comment]
Fixed by #393
