### ISSUE TITLE
ConstructionProblem needs unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#402]
`org.yarnandtail.andhow.internal.ConstructionProblem` has no unit test, resulting in [a lot of lines of untested code](https://codecov.io/gh/eeverman/andhow/src/master/andhow-core/src/main/java/org/yarnandtail/andhow/internal/ConstructionProblem.java).

Testing this class and its inner classes is not hard, but is a bit tricky because most of the ConstructionProblem types require other AndHow classes to be passed in the constructors.  **_Have no fear - Its doable!_**  Feel free to put in a work in progress merge request for early review and suggestions if needed.

**_What is a construction problem?_**
AndHow loads configuration for an application at startup and validates the configuration.  Problems found during validation are `ValidationProblem`s.  If, however, a problem is found that prevents AndHow from even beginning to load values, for instance a validation rule that is unenforcible like < 4 & > 100, that is a `Construction Problem`.  There are several types of construction problems and each has its own inner subclass to capture and report the details of the problem.

**Comment by chace86** [comment]
@eeverman have you considered using Mockito as part of testing? I only ask because it can often save having to make your own mock implementations of `Loader` interface. Also, if you use real implementations of Loader interface and the class name changes, it will break `getProblemContext`. Mockito can help avoid that.

https://site.mockito.org/

**Comment by eeverman** [comment]
Mockito sounds like it would be a nice solution and might simplify some other difficult to test situations - Mock away...

**Comment by jr7square** [comment]
Yup, I was actually planning on using Mockito. Should simplify things.

**Comment by eeverman** [comment]
@jr7square and @chace86 - Were one of you guys looking at taking this one?  I don't want us to accidentally have two people working on it.

**Comment by eeverman** [comment]
@jr7square Do you want me to add you as a collaborator on this project?  That should let you assign tasks to yourself.

**Comment by chace86** [comment]
I was under the assumption that @jr7square was working on this one. If that is not the case, I can work on it.

**Comment by jr7square** [comment]
Yeah, I'm working on it. Sorry for the confusion. Yeah you can add me @eeverman

**Comment by eeverman** [comment]
Fixed by PR #415 

Thanks @jr7square!

**Comment by eeverman** [comment]
Fixed by PR #415
