### ISSUE TITLE
IOUtil needs JavaDocs

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#416]
The methods in this class are relatively self explanitory, but they could use some JavaDocs.  The full classpath is `org.yarnandtail.andhow.util.IOUtil`

Also, the constant `USER_DIR_KEY` in this class is never used and should be removed.

**Comment by yirrilo** [comment]
Hello,
I'll take care of that issue.
Best regards !

**Comment by eeverman** [comment]
fix by PR #417
