### ISSUE TITLE
Consider the Interrobang‽

### ISSUE THREAD

**Issue by carlschroedl** [eeverman/andhow#435]
https://en.wikipedia.org/wiki/Interrobang

Picture:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Interrobang.svg/75px-Interrobang.svg.png)

Actual character:
### ‽

**Comment by carlschroedl** [comment]
Please don't actually use this -- it would be an SEO fail. Mostly just wanted to show you this is a thing :)

**Comment by eeverman** [comment]
Very cool to know that exists in the world.
Where are the other combos, like when you are waiting for a response, "And?"  The Amper-Interro.
Or if you trail off because you expect to be answered, "and then you said...?"  The Interrolipse.

I'll keep this open.  Right?!

**Comment by eeverman** [comment]
Time to close this one, eh‽
