### ISSUE TITLE
Merge changes in master branch into 0.5.0 branch

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#445]
**_This is a good first issue on this project if you are familiar with git and maven_**

The master branch has is working towards a 0.4.1 release that should be API compatible with 0.4.0.
The 0.5.0 branch has API changes that is not expected to be 100% compatible with the 0.4.x releases.

So far the 0.5.0 branch has some minor changes in it, but the master branch has advanced a lot.  To keep the 0.5.0 branch up to date, it needs to receive the changes from master occasionally - this would be a good time.

In the cases of a merge conflict, look at closed pull requests against the 0.5.0 branch to see what the intended change was.  Please list any resolved merge conflicts in comments to this task.

**Comment by code4t2** [comment]
Hi, 

May I please take up this issue?

**Comment by code4t2** [comment]
Since you're a few hours away, I took it up and committed the requested change. Kindly review.

**Comment by code4t2** [comment]
Done. Also changed the base to master. 

Ref #446

**Comment by eeverman** [comment]
Fixed by #446
