### ISSUE TITLE
String validation should accept argument arrays of acceptable values

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#45]
**_This is a bigger task, but is doable even if you are not very familiar with the project just by copying the code around this new feature_**

`org.yarnandtail.andhow.valid.StringValidator` has several simple inner classes that provide different ways of validating a String, e.g., `StartsWith`, `EndsWith`, and `Regex`.

Another way typical way to validate a string would be to have a small list of possible values, eg:  `match("http://", "https://")` or
`matchIgnoreCase("abc", "mno", "xyz")`

Users declaring `Properties` that have validation usually don't provide a validator class directly, instead, they use the builder associated with the property.  The builder for a Property is an inner class of the Property itself.  So for the String type Property, the builder is at `org.yarnandtail.andhow.property.StrProp.StrBuilder`.  That builder will need a new method to add the new match validators, something like `mustMatch(String... possibleValues)`

Suggestion:  Before starting on this task, make sure the example in the [Readme](https://github.com/eeverman/andhow) makes sense to you.  Post questions on this task if needed.  There is also an email list and Slack channel for discussions.

**Comment by rupeshA** [comment]
@eeverman , I am trying to understand the scope of work for this one.

**Comment by eeverman** [comment]
The key first step would be to add an implementation to the ‘StringValidator’ class that accepts an array or list of Strings that are considered acceptable values.

**Comment by eeverman** [comment]
@rupeshA You can always put in a Work In Progress (WIP) pull request after you start this task to ask for review of the work before you are complete.

**Comment by rupeshA** [comment]
https://github.com/eeverman/andhow/pull/453

**Comment by eeverman** [comment]
This has been fixed.
