### ISSUE TITLE
Update Javadoc documentation

### ISSUE THREAD

**Issue by code4t2** [eeverman/andhow#455]
Quite a few javadoc comments throughout several files have become outdated and need to be replaced or updated. 

These are not thrown up during the standard build process unless the lines 

```xml
<additionalJOption>-Xdoclint:none</additionalJOption>
<additionalJOption>-Xdoclint:-missing</additionalJOption>
<doclint>none,-missing</doclint>
```

are eliminated. 

Alternatively, they can also be displayed using a standard IDE's static linter (should turn up as a bunch of javadoc warnings, possibly 100+)

**Comment by eeverman** [comment]
@code4t2 Updating all the javadocs in the project is a big task - could you break this down into some smaller pieces?  Maybe by package?

**Comment by code4t2** [comment]
Sure, @eeverman I shall do that.

**Comment by eeverman** [comment]
Closing this task as it has been superceded.
