### ISSUE TITLE
AndHowCoreTestBase clears JNDI properties twice

### ISSUE THREAD

**Issue by chace86** [eeverman/andhow#461]
https://github.com/eeverman/andhow/blob/09bebf700c52de823539eb6e734cbc79cd3b5469/andhow-core/src/test/java/org/yarnandtail/andhow/AndHowCoreTestBase.java#L68-L84

`AndHowCoreTestBase` calls `.clear()` unnecessarily twice on `SimpleNamingContextBuilder` after test. Remove the duplicate and misnamed `clearJNDIBeforeTest()` method.

**Comment by eeverman** [comment]
Fixed by #463
