### ISSUE TITLE
ValueType implementations should have the static get method removed

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#465]
**_Note:  This task must be done against the 0.5.0 branch_**
`org.yarnandtail.andhow.valuetype.ValueType`

At some point, implementations of this class picked up two methods to fetch the singleton instance:
* `static get()`
* `static instance()`
Remove the `get()` method from all implementations.  It does not seem to be used anywhere.  If it is used somewhere, replace w/ `instance`.

**Comment by code4t2** [comment]
I was wondering if we could use the @Deprecated annoitation against the current release and then remove it for 0.5.0 . Thoughts, @eeverman

**Comment by code4t2** [comment]
Kindly review #468 , @eeverman

**Comment by eeverman** [comment]
Looks like you have this one fixed, @code4t2 so I will close.
