### ISSUE TITLE
Helpful javadocs - org.yarnandtail.andhow.valuetype

### ISSUE THREAD

**Issue by code4t2** [eeverman/andhow#466]
Adding helpful javadocs to AndHow, package-by-package. 

Worked on this package before or use it? Feel free to add helpful insights or tips

Related #455

**Comment by code4t2** [comment]
Plan to work with #465 to deprecate the get() on ValueTypes and remove them for 0.5.0.

**Comment by eeverman** [comment]
The java docs have evolved a lot since this ticket was open.
Thanks for your help on this, @code4t2 !
