### ISSUE TITLE
Release creates unneeded artifacts

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#499]
**Describe the bug**
Performing a release results in some modules that are only for testing being created and uploaded to the repo.  These should be trimmed off from the generated output  It would also be nice to exclude them from test coverage.

This would be a great first issue for someone new to the project who knows maven (and the maven release process) well.  The pom file uses the `nexus-staging-maven-plugin` to do the uploads to the Sonotype repo during releases.

The only modules that need to create artifacts that are actually uploaded to the repo during a release are:
* andhow (andhow-core and andhow-annotation-processor bundled as a single jar for easier use in projects)
* andhow-core (Interfaces and runtime of AndHow - doesn't include the annotation processor)
* andhow-annotation-processor (Only needed at compile time)
* andhow-test-harness (Useful utils for writing tests for projects using AndHow)
**...This list has changed since I wrote this up in June.  Newly added modules that also need to be included in the release:**
* **andhow-junit5-extensions (New library for testing apps w/ JUnit 5)**
* **andhow-shared-test-utils** (Test utils used by junit5-extensions and used internally)

**Comment by eeverman** [comment]
i think a lot of this has already been fixed while going thru pom files, but it would be good to test a release dry run to see if any extra jars are created.

**Comment by eeverman** [comment]
@alex-kar I'm hoping to get a new release out in the next week or so and this issue would be really nice to resolve.  Do you think you could take a look at it?

**Comment by alex-kar** [comment]
@eeverman Yes, sure.

**Comment by eeverman** [comment]
Fixed by #593
