### ISSUE TITLE
StdConfig.setSystemProperties should be deprecated similar to setEnvironmentProperties

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#510]
With fully functioning `setFixedValue` methods, there is no user use case for this method.
`setSystemProperties` and `setEnvironmentProperties` could be moved to AndHowCoreTestConfig to allow for easy testing of SysProp and EnvVar loaders.

Also, its implementation should be cleaned up and improved to match `setEnvironmentProperties`

**Comment by eeverman** [comment]
This is currently marked as deprecated in the javadoc, but not code.

**Comment by alex-kar** [comment]
> This is currently marked as deprecated in the javadoc, but not code.
Marked deprecated as part of #596
