### ISSUE TITLE
NamingStrategy.isUriNameDistict is misspelled

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#526]
**Describe the bug**
Just an obvious misspelling in a method name, here:
https://github.com/eeverman/andhow/blob/homepage/andhow-core/src/main/java/org/yarnandtail/andhow/api/NamingStrategy.java#L73
`isUriNameDistict` should be `isUriNameDistinct`

**Comment by eeverman** [comment]
This method is on an interface that is used by only one class and it is unlikely that anyone has ever created another implementation.  It would be OK to just rename it across the entire project.

**Comment by Jeyabal-B** [comment]
I will work on fixing this.

**Comment by eeverman** [comment]
Great - Thanks @Jeyabal-B

**Comment by alex-kar** [comment]
@eeverman Since this is an urgent issue, can I fix it?

**Comment by Jeyabal-B** [comment]
Hello,

Sorry I didn’t get a chance to work on it and I am currently out of town. I will be back only next week. I can finish it then.

**Comment by eeverman** [comment]
Thanks @Jeyabal-B for your willingness to help.  I'm eager to get the next release out, so I'm going to ask @alex-kar to work on this for now.
Please check back, @Jeyabal-B, there are more tasks coming and more chances to get involved!

**Comment by eeverman** [comment]
Fixed by #597
