### ISSUE TITLE
Switch to JaCoCo for code coverage

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#544]
**Describe the bug**
This project uses Cobertura for code coverage, however, Cobertura has been abandoned and has not been updated to support (even) JDK 8 language constructs.  Running Cobertura to generate coverage reports generates tons of errors, mostly for lambdas that it doesn't recognize.

As a result, the coverage reports are probably not correct and at some point they will break completely.

This task is to replace Cobertura with JaCoCo, or something similar.  JaCoco looks the most promising, but other proposals of a good coverage framework would be considered.  Here are the requirements:
* The project uses Maven, so Cobertura must be replaced in the [pom file](https://github.com/eeverman/andhow/blob/homepage/pom.xml) with a new framework
* Coverage reports should only be generated when explicitly run (i.e., don't generate a coverage report by default with each build).  This is likely the default for most code coverage maven plugins.
* The `.travis.yml` file needs to be updated to include the command to actually run the coverage report.  This is [currently configured to run Cobertura](https://github.com/eeverman/andhow/blob/homepage/.travis.yml#L10) and [upload the results to codecov.io](https://github.com/eeverman/andhow/blob/homepage/.travis.yml#L13).
* The generated report format will need to be supported by CodeCov - They support Cobertura and JaCoCo and likely others.

**Comment by alex-kar** [comment]
Can I take it?

**Comment by eeverman** [comment]
@alex-kar  You've got it - Thanks for the help!

**Comment by eeverman** [comment]
@alex-kar Please make sure you branch from the **main** branch, not the 'homepage' branch.  I've done that way too many times.  Here are some [notes for new developers on this project](https://sites.google.com/view/andhow/developer).

**Comment by eeverman** [comment]
Fixed by #549.
Thanks @alex-kar!
