### ISSUE TITLE
Deprecate one KeyValuePairLoader.setKeyValuePairs method

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#552]
**Describe the bug**
The two set `setKeyValuePairs` methods in [KeyValuePairLoader](https://github.com/eeverman/andhow/blob/main/andhow-core/src/main/java/org/yarnandtail/andhow/load/KeyValuePairLoader.java) behave slightly differently and the one that takes an array is only used for testing.

ToDo:
* Deprecate the [`KeyValuePairLoader.setKeyValuePairs(String... keyValuePairs)`](https://github.com/eeverman/andhow/blob/69af75fc21aaf7194ecbf5df7bb62613755374c7/andhow-core/src/main/java/org/yarnandtail/andhow/load/KeyValuePairLoader.java#L74) method
* For now, the deprecated method should just convert to a List and call the `setKeyValuePairs(List<String>)` method.
* Ensure current test cover both methods, but the method and any test using it will need to be removed in the next major release.

**Comment by alex-kar** [comment]
@eeverman I would like to work on it.

**Comment by eeverman** [comment]
@alex-kar  Certainly - Feel free to self-assign any help wanted issue.

**Comment by eeverman** [comment]
Nice fix, @alex-kar
