### ISSUE TITLE
Two of the loaders have 'add' behavior for 'set' methods

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#555]
**Describe the bug**
Two of the loaders in the loader package perform an `add` when `set` is called.  They also ignore null and empty values.  The expected behavior for both would be:
* Completely replace values when `set` is called
* Set the associated collection to empty or null when `set` is called with null or empty.

The logic in MapLoader around the `map` field and `setMap` method is acceptable for these other methods, that is, letting the field's initial value be null and setting it to null if null is passed.  That can be verified by checking each loader's `load` method to ensure that there is a null check before the field is used.

Here is the list of loader methods that this applies to, all in the `org.yarnandtail.andhow.load` package:
* `FixedValueLoader.setPropertyValues` (see other issue about deprecating one of these methods)
* `FixedValueLoader.setKeyObjectPairValues`
* `KeyValuePairLoader.setKeyValuePairs`

Also update tests and docs to match.

**Comment by eeverman** [comment]
@alex-kar I think you are pretty familiar with the code in these classes now - Can you take a look?

**Comment by alex-kar** [comment]
@eeverman Yes, sure.

**Comment by eeverman** [comment]
Fixed by #583
