### ISSUE TITLE
StaticPropertyConfiguration and similar should have 'static' removed from name

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#622]
StaticPropertyConfiguration was intended to distinguish static (per class) from Instance.  However, the AndHow project has solidly become static only, so the 'static' prefix should be removed since it has no meaning.

**Comment by alex-kar** [comment]
I would like to take it.

Here's what I've found so far:
StaticPropertyConfiguration
StaticPropertyConfigurationInternal
StaticPropertyConfigurationImmutable
StaticPropertyConfigurationImmutableTest
StaticPropertyConfigurationMutable
StaticPropertyConfigurationImmutableTest

**Comment by eeverman** [comment]
You got it, @alex-kar

**Comment by eeverman** [comment]
@alex-kar - I added the 'hacktoberfest' tag to the project so you get a free tee-shirt:
https://hacktoberfest.digitalocean.com/faq

**Comment by eeverman** [comment]
Fixed by #632
