### ISSUE TITLE
AndHowLogHandler needs better unit testing

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow#668]
The [AndHowLogHandler](https://github.com/eeverman/andhow/blob/de7de6574c5e75ab76fa468e1249686a1098746a/andhow-core/src/main/java/org/yarnandtail/andhow/util/AndHowLogHandler.java#L10) has [15 untested lines and 5 partials](https://app.codecov.io/gh/eeverman/andhow/blob/main/andhow-core/src/main/java/org/yarnandtail/andhow/util/AndHowLogHandler.java) and they would be relatively easy to test.  A [test already exists](https://github.com/eeverman/andhow/blob/de7de6574c5e75ab76fa468e1249686a1098746a/andhow-core/src/test/java/org/yarnandtail/andhow/util/AndHowLogHandlerTest.java#L13), so just add to it.

It's important that this class not throw exceptions for any type of input.  Since this is a very low-level log, we really don't want this to throw errors in the middle of reporting something.

. . .

Why does this project have a logging system in the first place??

AndHow is a configuration utility.  AndHowLog is used to let AndHow do logging _prior to the application logging system being configured_. Configuration values loaded by AndHow could be used to configure the application's logging system, so AndHow's logging cannot assume 'normal' logging is available to it.

**Comment by emafazillah** [comment]
Hi @eeverman, can I work on this ticket?

**Comment by eeverman** [comment]
@emafazillah - Its yours - Thank you!

**Comment by eeverman** [comment]
@emafazillah - I hope all is well.
Are you still interested in this ticket?

**Comment by emafazillah** [comment]
> @emafazillah - I hope all is well. Are you still interested in this ticket?

Yes, I am. However, I still have 1 line partially covered and 1 line uncovered.

**Comment by eeverman** [comment]
Fixed by MR #686
